# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(830, 681)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, -20, 891, 721))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-10, -20, 861, 731))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("desktop-wallpaper-logo-full-backgrounds-logo-ferrari.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 110, 631, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mevcutaraclar = QtWidgets.QPushButton(self.layoutWidget)
        self.mevcutaraclar.setObjectName("mevcutaraclar")
        self.verticalLayout.addWidget(self.mevcutaraclar)
        self.aracgiris = QtWidgets.QPushButton(self.layoutWidget)
        self.aracgiris.setObjectName("aracgiris")
        self.verticalLayout.addWidget(self.aracgiris)
        self.araccikis = QtWidgets.QPushButton(self.layoutWidget)
        self.araccikis.setObjectName("araccikis")
        self.verticalLayout.addWidget(self.araccikis)
        self.kayitliaraclar = QtWidgets.QPushButton(self.layoutWidget)
        self.kayitliaraclar.setObjectName("kayitliaraclar")
        self.verticalLayout.addWidget(self.kayitliaraclar)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(220, 40, 391, 41))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.mevcutaraclar.setText(_translate("Form", "Mevcut Araçlar"))
        self.aracgiris.setText(_translate("Form", "Araç Girişi"))
        self.araccikis.setText(_translate("Form", "Araç Çıkışı"))
        self.kayitliaraclar.setText(_translate("Form", "Kayıtlı Araçlar"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">ANA SAYFA</span></p></body></html>"))
