# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'araccikis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1165, 689)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-30, -50, 1221, 771))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("desktop-wallpaper-logo-full-backgrounds-logo-ferrari.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.plaka = QtWidgets.QLineEdit(Form)
        self.plaka.setGeometry(QtCore.QRect(900, 280, 141, 31))
        self.plaka.setObjectName("plaka")
        self.odenecektutar = QtWidgets.QLineEdit(Form)
        self.odenecektutar.setGeometry(QtCore.QRect(900, 410, 141, 31))
        self.odenecektutar.setObjectName("odenecektutar")
        self.odemeyial = QtWidgets.QPushButton(Form)
        self.odemeyial.setGeometry(QtCore.QRect(760, 520, 101, 41))
        self.odemeyial.setObjectName("odemeyial")
        self.aracsec = QtWidgets.QPushButton(Form)
        self.aracsec.setGeometry(QtCore.QRect(210, 620, 101, 41))
        self.aracsec.setObjectName("aracsec")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 80, 161, 41))
        self.label_2.setObjectName("label_2")
        self.aracgoruntu = QtWidgets.QGraphicsView(Form)
        self.aracgoruntu.setGeometry(QtCore.QRect(50, 130, 451, 461))
        self.aracgoruntu.setObjectName("aracgoruntu")
        self.cikisiniyap = QtWidgets.QPushButton(Form)
        self.cikisiniyap.setGeometry(QtCore.QRect(940, 520, 101, 41))
        self.cikisiniyap.setObjectName("cikisiniyap")
        self.kaldigisuree = QtWidgets.QLineEdit(Form)
        self.kaldigisuree.setGeometry(QtCore.QRect(900, 340, 141, 31))
        self.kaldigisuree.setObjectName("kaldigisuree")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 381, 41))
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(740, 240, 151, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plakagoster = QtWidgets.QPushButton(self.layoutWidget)
        self.plakagoster.setObjectName("plakagoster")
        self.verticalLayout.addWidget(self.plakagoster)
        self.kaldigisure = QtWidgets.QPushButton(self.layoutWidget)
        self.kaldigisure.setObjectName("kaldigisure")
        self.verticalLayout.addWidget(self.kaldigisure)
        self.odenecektutar_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.odenecektutar_2.setObjectName("odenecektutar_2")
        self.verticalLayout.addWidget(self.odenecektutar_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.odemeyial.setText(_translate("Form", "Ödemeyi Al"))
        self.aracsec.setText(_translate("Form", "Girecek Aracı Seç"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Araç Görüntüsü</span></p></body></html>"))
        self.cikisiniyap.setText(_translate("Form", "Çıkışını Yap"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">ARAÇ ÇIKIŞI</span></p></body></html>"))
        self.plakagoster.setText(_translate("Form", "Plaka"))
        self.kaldigisure.setText(_translate("Form", "Kaldığı Süre"))
        self.odenecektutar_2.setText(_translate("Form", "Ödenecek Tutar"))
