# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayitliaraclar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(949, 715)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-30, -40, 1071, 771))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("desktop-wallpaper-logo-full-backgrounds-logo-ferrari.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.aracikaldir = QtWidgets.QPushButton(Form)
        self.aracikaldir.setGeometry(QtCore.QRect(560, 570, 141, 41))
        self.aracikaldir.setObjectName("aracikaldir")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 341, 51))
        self.label_2.setObjectName("label_2")
        self.araclarigoster = QtWidgets.QPushButton(Form)
        self.araclarigoster.setGeometry(QtCore.QRect(160, 580, 111, 41))
        self.araclarigoster.setObjectName("araclarigoster")
        self.araclar = QtWidgets.QTableWidget(Form)
        self.araclar.setGeometry(QtCore.QRect(70, 130, 301, 421))
        self.araclar.setObjectName("araclar")
        self.araclar.setColumnCount(0)
        self.araclar.setRowCount(0)
        self.aracplaka1 = QtWidgets.QLineEdit(Form)
        self.aracplaka1.setGeometry(QtCore.QRect(630, 500, 151, 31))
        self.aracplaka1.setObjectName("aracplaka1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(440, 490, 161, 51))
        self.label_3.setObjectName("label_3")
        self.aracsahibi = QtWidgets.QLineEdit(Form)
        self.aracsahibi.setGeometry(QtCore.QRect(770, 130, 151, 31))
        self.aracsahibi.setObjectName("aracsahibi")
        self.telno = QtWidgets.QLineEdit(Form)
        self.telno.setGeometry(QtCore.QRect(770, 210, 151, 31))
        self.telno.setObjectName("telno")
        self.aracplaka2 = QtWidgets.QLineEdit(Form)
        self.aracplaka2.setGeometry(QtCore.QRect(770, 290, 151, 31))
        self.aracplaka2.setObjectName("aracplaka2")
        self.aracekle = QtWidgets.QPushButton(Form)
        self.aracekle.setGeometry(QtCore.QRect(720, 370, 141, 41))
        self.aracekle.setObjectName("aracekle")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(630, 110, 133, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.aracikaldir.setText(_translate("Form", "Aracı Kaldır"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Sisteme Kayıtlı Araçlar </span></p></body></html>"))
        self.araclarigoster.setText(_translate("Form", "Göster"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Araç Plaka :</span></p></body></html>"))
        self.aracekle.setText(_translate("Form", "Aracı Ekle"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Araç Sahibi :</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Tel No :</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Araç Plaka :</span></p></body></html>"))
