# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mevcutaraclar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(945, 692)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-40, -60, 1041, 771))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("desktop-wallpaper-logo-full-backgrounds-logo-ferrari.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.aracgetir = QtWidgets.QPushButton(Form)
        self.aracgetir.setGeometry(QtCore.QRect(150, 530, 121, 41))
        self.aracgetir.setObjectName("aracgetir")
        self.mevcutaraclar = QtWidgets.QTableWidget(Form)
        self.mevcutaraclar.setGeometry(QtCore.QRect(50, 200, 301, 301))
        self.mevcutaraclar.setDragEnabled(False)
        self.mevcutaraclar.setObjectName("mevcutaraclar")
        self.mevcutaraclar.setColumnCount(0)
        self.mevcutaraclar.setRowCount(0)
        self.aracguncelle = QtWidgets.QPushButton(Form)
        self.aracguncelle.setGeometry(QtCore.QRect(700, 510, 121, 41))
        self.aracguncelle.setObjectName("aracguncelle")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(140, 50, 641, 61))
        self.label_6.setObjectName("label_6")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(620, 200, 144, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(780, 180, 135, 311))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.giristarih = QtWidgets.QLineEdit(self.layoutWidget1)
        self.giristarih.setObjectName("giristarih")
        self.verticalLayout_2.addWidget(self.giristarih)
        self.kalacagisure = QtWidgets.QLineEdit(self.layoutWidget1)
        self.kalacagisure.setObjectName("kalacagisure")
        self.verticalLayout_2.addWidget(self.kalacagisure)
        self.aracplaka = QtWidgets.QLineEdit(self.layoutWidget1)
        self.aracplaka.setObjectName("aracplaka")
        self.verticalLayout_2.addWidget(self.aracplaka)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.aracgetir.setText(_translate("Form", "Getir"))
        self.aracguncelle.setText(_translate("Form", "Güncelle"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">MEVCUT ARAÇLAR</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Giriş Tarihi :</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Kalacağı Süre :</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Araç Plaka :</span></p></body></html>"))
